################################################################################
###
### DATE CREATED: 2025-06-06
###
### AUTHOR: Mark Wheldon
###
### PROJECT: TFR Stalls
###
### DESCRIPTION: Setup and helpers for slowTests. This must be run before any
### other files in this directory.
###
###-----------------------------------------------------------------------------
###
################################################################################


###-----------------------------------------------------------------------------
### * Set Up

library(here)
library(pbapply)
library(tfrSURFs)
library(testthat)
library(withr)

###-----------------------------------------------------------------------------
### * Functions

##' Create all combinations of arguments for `make_tfr_surfs_xxx()` functions.
##'
##' @return A data frame
##' @author Mark C Wheldon
##' @keywords internal
make_tfr_surfs_param_df <- function() {
    outdf <-
        expand.grid(median_only = c(FALSE, TRUE),
                    transition_condition_type = get_arg_defs(make_tfr_surfs,
                                                        "transition_condition_type"),
                    rate_threshold = c(0, 0.01),
                    rate_prob_threshold = c(0.5, 0.8),
                    exceedance_condition = get_arg_defs(make_tfr_surfs, "exceedance_condition"),
                    exceedance_condition_prob_threshold = c(0.5, 0.8),
                    min_surf_length = c(1, 2),
                    min_inter_surf_length = c(1, 2),
                    continuation_condition = get_arg_defs(make_tfr_surfs, "continuation_condition"),
                    continuation_condition_prob_threshold = c(0.5, 0.8),
                    smoothing_method = get_arg_defs(make_tfr_surfs, "smoothing_method"),
                    bandwidth = c(3, 5),
                    incl_small_countries = c(FALSE, TRUE),
                    stringsAsFactors = FALSE)

    ## 'smoothing_method = "moving_average"' not implemented
    outdf <- outdf[outdf[["smoothing_method"]] != "moving_average", ]

    return(outdf)
}


##' Locate and unpack a short run of bayesTFR for testing
##'
##' A complete set of TFR projections produced by the \pkg{bayesTFR} package is
##' required for several of the tests included in the package. Given the
##' location of a \file{.tar.gz} archive of such a run, this function will
##' unpack it to a temporary location and return the directory path. If
##' \code{take_down = TRUE} (the default), the directory will be deleted when
##' the R session quits. This function is primarily designed for running tests
##' during development. The archive itself is too large to be distributed with
##' the package, so the user will need to prepare it manually if this function
##' is to be use (see the documentation for \pkg{bayesTFR}).
##'
##' The archive will need to contain both estimates and projections of TFR.
##' Projections are generated by \code{\link[bayesTFR]{tfr.predict}}. If
##' \code{check = TRUE}, \code{\link[bayesTFR]{has.tfr.prediction}} will be run
##' on the unpacked archive to check that projections have been generated.
##'
##' @param file File path to a \file{.tar.gz} archive of a
##'     complete set of TFR projections from \pkg{bayesTFR}.
##' @param overwrite Logical; should any existing results be overwritten?
##' @param checks Logical; run checks on the unpacked projections to ensure they
##'     are complete?
##' @param take_down Logical; delete the
##' @param verbose Logical; print various messages.
##' @return File path to the directory containing the unpacked TFR projections.
##' @author Mark C Wheldon
##' @keywords internal
setup_bayesTFR_test_data_temp_dir <- function(file, overwrite = FALSE, checks = TRUE, take_down = TRUE, verbose = TRUE) {
    archive_name <- strsplit(basename(file), "\\.")[[1]][1]
    temp_dir <- tempdir()
    bayesTFR_output_dir <- normalizePath(file.path(temp_dir, archive_name), mustWork = FALSE)
    if (!dir.exists(bayesTFR_output_dir) || overwrite) {
        files <- untar(file, list = TRUE, exdir = temp_dir,
                       tar = "internal")
        if (checks) {
            dirs <- unique(sapply(strsplit(files, "/"), "[[", 1))
            if (length(dirs) > 1)
                stop("Something is wrong with the archive: Multiple subdirectories would be created.")
        }
        success <- untar(file, list = FALSE, exdir = temp_dir,
                         tar = "internal")
        if (!identical(success, 0L))
            stop("Something went wrong 'untar'ing '", file, "' to '",
                 temp_dir, "'.")
        bayesTFR_output_dir <- normalizePath(file.path(temp_dir, dirs))
        if (verbose)
            message("'bayesTFR' test run unpacked to '", bayesTFR_output_dir, "'.")
    } else {
        if (verbose) message("'bayesTFR' test run is at: '", bayesTFR_output_dir, "'.")
    }
    if (checks) {
        if (!bayesTFR::has.tfr.prediction(bayesTFR_output_dir))
            stop("'bayesTFR::has.tfr.prediction()' failed for '",
                 bayesTFR_output_dir, "'.")
    }
    if (take_down) {
        withr::defer(expr = unlink(bayesTFR_output_dir, recursive = TRUE),
                     envir = globalenv())
        if (verbose) message("'", bayesTFR_output_dir, "' will be deleted when this R session quits.")
        }
    return(normalizePath(bayesTFR_output_dir))
}

###-----------------------------------------------------------------------------
### * Helper Functions

###-----------------------------------------------------------------------------
### ** Testthat Helpers

## 'source()' will source into global environment by default

## installed_test_src <- system.file("tests", "testthat", "setup.R", package = "tfrSURFs")
## if (file.exists(installed_test_src)) {
##     source(installed_test_src)
## } else source(here::here("tests", "testthat", "setup.R"))

for (x in dir(system.file("tests", "testthat", package = "tfrSURFs"),
              pattern = "^helper.*[.][RrSsQq]$", full.names = TRUE)) {
    source(x)
}
